###
GET https://9440-14-225-192-183.ngrok-free.app/webhook?hub.mode=subscribe&hub.verify_token=giabao2709&hub.challenge=BaoTram

### Get started
POST http://localhost:8100/webhook
Content-Type: application/json

{
  "object": "page",
  "entry": [
    {
      "id": "123456789",
      "time": 1458692752478,
      "messaging": [
        {
  "sender": { "id": 8268419943208957 },
  "recipient": { "id": 104122992539521 },
  "timestamp": 1723017321681,
  "postback": {
    "title": "Get Started",
    "payload": "GET_STARTED",
    "mid": "m_DHgDJam8A0LsQYu6o_sIuHlAHXciPnv1sHCjwzgprx3vmSnuMEU01Imfu-4VicFKJw2OP3n5L42PiOSlT4b2ww"
  }
}
      ]
    }
  ]
}

###
POST http://localhost:8100/setup-persistent-menu

###
POST http://localhost:8100/setup-get-started

###
POST http://localhost:8100/setup-nlp